const nodemailer = require("nodemailer");

// Create a reusable Ethereal tester account (perfect for proof of concepts)
// It doesn't require real API keys and gives you a URL to view the email.
let transporter;
async function initTransporter() {
  if (!transporter) {
    const testAccount = await nodemailer.createTestAccount();
    transporter = nodemailer.createTransport({
      host: "smtp.ethereal.email",
      port: 587,
      secure: false,
      auth: {
        user: testAccount.user,
        pass: testAccount.pass,
      },
    });
    console.log(`[EMAIL] Ethereal SMTP ready. Sender: ${testAccount.user}`);
  }
  return transporter;
}

async function sendPhysicianReport(toEmail, patientName, period, pdfBuffer) {
  const mailer = await initTransporter();
  
  const info = await mailer.sendMail({
    from: '"GlycoFriend" <reports@glycofriend.rw>',
    to: toEmail,
    subject: `GlycoFriend Report — ${patientName} — ${period}`,
    text: `Please find attached the glucose report for ${patientName} covering ${period}. Generated by GlycoFriend.`,
    attachments: [
      {
        filename: `GlycoFriend_Report_${patientName.replace(/\s+/g, "_")}_${period.replace(/\s+/g, "_")}.pdf`,
        content: pdfBuffer,
        contentType: "application/pdf"
      },
    ],
  });

  console.log(`\n📧 [EMAIL SENT TO PHYSICIAN]`);
  console.log(`Preview URL: ${nodemailer.getTestMessageUrl(info)}\n`);
  return { delivered: true, previewUrl: nodemailer.getTestMessageUrl(info) };
}

async function sendCHWAlert(toEmail, patientName, pdfBuffer) {
  const mailer = await initTransporter();

  const info = await mailer.sendMail({
    from: '"GlycoFriend" <reports@glycofriend.rw>',
    to: toEmail,
    subject: `GlycoFriend Alert — ${patientName} needs follow-up`,
    text: `A CHW alert has been triggered for ${patientName}. Please see the attached report for details.`,
    attachments: [
      {
        filename: `GlycoFriend_CHWAlert_${patientName.replace(/\s+/g, "_")}.pdf`,
        content: pdfBuffer,
        contentType: "application/pdf"
      },
    ],
  });

  console.log(`\n📧 [EMAIL SENT TO CHW]`);
  console.log(`Preview URL: ${nodemailer.getTestMessageUrl(info)}\n`);
  return { delivered: true, previewUrl: nodemailer.getTestMessageUrl(info) };
}

module.exports = { sendPhysicianReport, sendCHWAlert };
